import { fileURLToPath } from 'node:url'

import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

/**
 * One project only, unlike the seven backend services.
 *
 * They split `unit` from `integration` because their integration suite talks to a real Redis cluster
 * and a real MongoDB. This app talks to neither: every test runs in jsdom against a mocked urql
 * client, so there is nothing to isolate and no second project to run.
 *
 * Coverage is gated at 100 on all four metrics, the same as every other repo on the platform. The
 * exclusions below are code that is not this app's to test — generated codegen output, the DOM
 * bootstrap that only runs in a browser, and the Sentry init that is a single side-effecting call.
 */
export default defineConfig({
	plugins: [react()],
	resolve: {
		alias: {
			'@': fileURLToPath(new URL('./src', import.meta.url)),
			'@gql': fileURLToPath(new URL('./src/gql', import.meta.url))
		}
	},
	test: {
		globals: true,
		environment: 'jsdom',
		// Every date on the operator screens is formatted through `Intl`, which reads the ambient zone.
		// Without a fixed one the same assertion passes in Rome and fails in UTC — and the failure is an
		// hour, which reads as a bug in the formatter rather than as a machine difference.
		//
		// The test scripts export `TZ=UTC` as well, and both are needed. This setting reaches the worker
		// through `process.env`, which is enough for vitest's own pool; Stryker's runner uses a pool where
		// assigning `process.env.TZ` does not move ICU's zone, and its dry run failed on a `Europe/Rome`
		// machine with an assertion an hour out. A process-level `TZ` is the only one that always holds.
		env: { TZ: 'UTC' },
		// Order matters: the polyfill has to run before anything imports react-dom, and `vitest.setup.ts`
		// imports it transitively on its second line. See the file for what breaks without it.
		setupFiles: ['./vitest.polyfill.ts', './vitest.setup.ts'],
		include: ['test/**/*.test.{ts,tsx}'],
		restoreMocks: true,
		// The GraphQL helper replaces `globalThis.fetch`. Without this the replacement outlives the test
		// that installed it, and the next file's first request answers with the previous file's fixture.
		unstubGlobals: true,
		coverage: {
			provider: 'v8',
			reporter: ['text', 'html', 'lcov'],
			include: ['src/**/*.{ts,tsx}'],
			exclude: [
				// Generated by graphql-codegen on every `yarn codegen`. Editing it is pointless and
				// testing it tests the generator.
				'src/gql/**',
				// `createRoot(...).render(...)` — runs only against a real document, and the one thing
				// it could get wrong (mounting the wrong tree) is what every other test already covers.
				'src/main.tsx',
				// A single `Sentry.init` call guarded by a DSN check. Asserting it was called asserts
				// that the SDK exists.
				'src/instrument.ts',
				'src/vite-env.d.ts'
			],
			thresholds: {
				statements: 100,
				branches: 100,
				functions: 100,
				lines: 100
			}
		}
	}
})
